# Importing Taxis Dataset

In [ ]:
import seaborn as sns
data=sns.load_dataset('taxis')
data.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

**Checking datatypes ofcolumns**

In [ ]:
print(data.dtypes)

pickup             datetime64[ns]
dropoff            datetime64[ns]
passengers                  int64
distance                  float64
fare                      float64
tip                       float64
tolls                     float64
total                     float64
color                      object
payment                    object
pickup_zone                object
dropoff_zone               object
pickup_borough             object
dropoff_borough            object
dtype: object

**Missing values**

In [ ]:
data.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [ ]:
import pandas as pd
data['pickup']=pd.to_datetime(data['pickup'])
data['dropoff']=pd.to_datetime(data['dropoff'])

In [ ]:
data.dtypes

passengers            int64
distance            float64
fare                float64
tip                 float64
tolls               float64
total               float64
color                object
payment              object
pickup_zone          object
dropoff_zone         object
pickup_borough       object
dropoff_borough      object
pickup_date          object
pickup_time          object
pickup_hour           int32
pickup_dayofweek     object
dropoff_date         object
dropoff_time         object
dropoff_hour          int32
dtype: object

**Extract pickup date and time components**

In [ ]:
data['pickup_date'] = data['pickup'].dt.date
data['pickup_time'] = data['pickup'].dt.time
data['pickup_hour'] = data['pickup'].dt.hour
data['pickup_dayofweek'] = data['pickup'].dt.day_name()

In [ ]:
data['dropoff_date'] = data['dropoff'].dt.date
data['dropoff_time'] = data['dropoff'].dt.time
data['dropoff_hour'] = data['dropoff'].dt.hour

In [ ]:
data.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,...,dropoff_zone,pickup_borough,dropoff_borough,pickup_date,pickup_time,pickup_hour,pickup_dayofweek,dropoff_date,dropoff_time,dropoff_hour
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,...,UN/Turtle Bay South,Manhattan,Manhattan,2019-03-23,20:21:09,20,Saturday,2019-03-23,20:27:24,20
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,...,Upper West Side South,Manhattan,Manhattan,2019-03-04,16:11:55,16,Monday,2019-03-04,16:19:00,16
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,...,West Village,Manhattan,Manhattan,2019-03-27,17:53:01,17,Wednesday,2019-03-27,18:00:25,18
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,...,Yorkville West,Manhattan,Manhattan,2019-03-10,01:23:59,1,Sunday,2019-03-10,01:49:51,1
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,...,Yorkville West,Manhattan,Manhattan,2019-03-30,13:27:42,13,Saturday,2019-03-30,13:37:14,13

**Dropping unecessary columns(pickup dropoff)**

In [ ]:
data.drop(['pickup','dropoff'],axis=1,inplace=True)

In [ ]:
data.head()

,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,pickup_date,pickup_time,pickup_hour,pickup_dayofweek,dropoff_date,dropoff_time,dropoff_hour
0,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,2019-03-23,20:21:09,20,Saturday,2019-03-23,20:27:24,20
1,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,2019-03-04,16:11:55,16,Monday,2019-03-04,16:19:00,16
2,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,2019-03-27,17:53:01,17,Wednesday,2019-03-27,18:00:25,18
3,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,2019-03-10,01:23:59,1,Sunday,2019-03-10,01:49:51,1
4,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,2019-03-30,13:27:42,13,Saturday,2019-03-30,13:37:14,13

In [ ]:
data.shape

(6433, 19)

**Filling Missing Values**

In [ ]:
data['payment'].fillna(data['payment'].mode()[0], inplace=True)
data['pickup_zone'].fillna('Unknown', inplace=True)
data['dropoff_zone'].fillna('Unknown', inplace=True)
data['pickup_borough'].fillna('Unknown', inplace=True)
data['dropoff_borough'].fillna('Unknown', inplace=True)

<ipython-input-13-3259031681>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['payment'].fillna(data['payment'].mode()[0], inplace=True)
<ipython-input-13-3259031681>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['pickup_zone'].fillna('Unknown', inplace=True)
<ipython-input-13-3259031681>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['dropoff_zone'].fillna('Unknown', inplace=True)
<ipython-input-13-3259031681>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['pickup_borough'].fillna('Unknown', inplace=True)
<ipython-input-13-3259031681>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['dropoff_borough'].fillna('Unknown', inplace=True)

In [ ]:
data.isnull().sum()

passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment             0
pickup_zone         0
dropoff_zone        0
pickup_borough      0
dropoff_borough     0
pickup_date         0
pickup_time         0
pickup_hour         0
pickup_dayofweek    0
dropoff_date        0
dropoff_time        0
dropoff_hour        0
dtype: int64

passengers (int64)

This column shows how many passengers were in the taxi.

Value counts → are there any weird numbers like 0 or >6?

Distribution → most rides are likely to have 1–3 passengers.

In [ ]:
print(data['passengers'].value_counts())

passengers
1    4678
2     876
5     277
3     243
6     153
4     110
0      96
Name: count, dtype: int64

In [ ]:
data[data['passengers'] == 0]

,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,pickup_date,pickup_time,pickup_hour,pickup_dayofweek,dropoff_date,dropoff_time,dropoff_hour
7,0,1.4,8.5,0.00,0.00,11.80,yellow,credit card,Murray Hill,Flatiron,Manhattan,Manhattan,2019-03-22,12:47:13,12,Friday,2019-03-22,12:58:17,12
14,0,2.9,11.5,0.00,0.00,14.80,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan,2019-03-27,12:13:34,12,Wednesday,2019-03-27,12:25:48,12
41,0,4.5,20.0,0.00,0.00,23.30,yellow,cash,TriBeCa/Civic Center,Kips Bay,Manhattan,Manhattan,2019-03-24,18:42:56,18,Sunday,2019-03-24,19:09:00,19
92,0,10.6,33.5,0.00,5.76,40.06,yellow,credit card,East Tremont,Midtown East,Bronx,Manhattan,2019-03-28,07:05:19,7,Thursday,2019-03-28,07:41:14,7
117,0,3.6,15.5,3.75,0.00,22.55,yellow,credit card,Yorkville East,Penn Station/Madison Sq West,Manhattan,Manhattan,2019-03-23,09:39:25,9,Saturday,2019-03-23,09:56:45,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5187,0,2.2,9.0,3.05,0.00,13.35,yellow,credit card,LaGuardia Airport,Jackson Heights,Queens,Queens,2019-03-05,00:42:20,0,Tuesday,2019-03-05,00:51:13,0
5207,0,2.1,13.0,0.00,0.00,16.30,yellow,credit card,Penn Station/Madison Sq West,Lincoln Square East,Manhattan,Manhattan,2019-03-19,12:30:27,12,Tuesday,2019-03-19,12:49:12,12
5280,0,3.6,14.0,4.45,0.00,22.25,yellow,credit card,Upper West Side North,Penn Station/Madison Sq West,Manhattan,Manhattan,2019-03-15,23:33:56,23,Friday,2019-03-15,23:51:39,23
5741,0,3.0,14.5,3.05,0.00,18.35,green,credit card,Central Harlem North,Manhattan Valley,Manhattan,Manhattan,2019-03-30,13:29:38,13,Saturday,2019-03-30,13:48:18,13
6080,0,0.0,8.0,0.00,0.00,8.00,green,credit card,Fort Greene,Fort Greene,Brooklyn,Brooklyn,2019-03-15,20:42:08,20,Friday,2019-03-15,20:42:18,20

**Replacing 0 passengers with mode value 1**

In [ ]:
data.loc[data['passengers'] == 0, 'passengers'] = 1

In [ ]:
print(data['passengers'].value_counts())

passengers
1    4774
2     876
5     277
3     243
6     153
4     110
Name: count, dtype: int64

**Analyzing each column**

In [ ]:
print(data['distance'].describe())
print(data['distance'].value_counts().sort_index().head(10))  # check small values

count    6433.000000
mean        3.024617
std         3.827867
min         0.000000
25%         0.980000
50%         1.640000
75%         3.210000
max        36.700000
Name: distance, dtype: float64
distance
0.00    51
0.01     1
0.02     3
0.03     1
0.04     1
0.07     3
0.08     1
0.09     2
0.10     7
0.11     1
Name: count, dtype: int64

In [ ]:
print(data['fare'].describe())
print(data['fare'].value_counts().sort_index().head(20))  # View low-end fares
print(data['fare'].value_counts().sort_index(ascending=False).head(20))  # High-end fares

count    6433.000000
mean       13.091073
std        11.551804
min         1.000000
25%         6.500000
50%         9.500000
75%        15.000000
max       150.000000
Name: fare, dtype: float64
fare
1.0       1
2.5      39
3.0      31
3.5      97
4.0     154
4.5     217
5.0     313
5.5     312
6.0     345
6.5     323
7.0     296
7.5     350
8.0     258
8.5     254
9.0     201
9.5     229
10.0    199
10.5    179
11.0    159
11.5    160
Name: count, dtype: int64
fare
150.00    2
143.50    1
130.00    1
120.00    1
103.00    1
100.00    1
96.50     1
93.50     1
87.50     1
86.14     1
84.00     1
81.86     1
80.00     1
79.50     1
78.00     1
75.50     1
72.00     1
71.20     1
70.00     2
69.06     1
Name: count, dtype: int64

In [ ]:
data['tolls'].value_counts().sort_index().tail(10)

tolls
6.12     2
8.40     1
8.50     1
9.50     1
11.52    4
12.50    2
16.26    1
17.28    1
18.90    1
24.02    1
Name: count, dtype: int64

In [ ]:
data[data['total'] == 0]

Empty DataFrame
Columns: [passengers, distance, fare, tip, tolls, total, color, payment, pickup_zone, dropoff_zone, pickup_borough, dropoff_borough, pickup_date, pickup_time, pickup_hour, pickup_dayofweek, dropoff_date, dropoff_time, dropoff_hour]
Index: []

In [ ]:
data['color'].value_counts()

color
yellow    5451
green      982
Name: count, dtype: int64

**Encoding data**

In [ ]:
# Columns to encode
encode_cols = ['color', 'payment', 'pickup_borough', 'dropoff_borough', 'pickup_dayofweek']

data_encoded = pd.get_dummies(data, columns=encode_cols, drop_first=True)
data_encoded.head()

,passengers,distance,fare,tip,tolls,total,pickup_zone,dropoff_zone,pickup_date,pickup_time,...,dropoff_borough_Manhattan,dropoff_borough_Queens,dropoff_borough_Staten Island,dropoff_borough_Unknown,pickup_dayofweek_Monday,pickup_dayofweek_Saturday,pickup_dayofweek_Sunday,pickup_dayofweek_Thursday,pickup_dayofweek_Tuesday,pickup_dayofweek_Wednesday
0,1,1.60,7.0,2.15,0.0,12.95,Lenox Hill West,UN/Turtle Bay South,2019-03-23,20:21:09,...,True,False,False,False,False,True,False,False,False,False
1,1,0.79,5.0,0.00,0.0,9.30,Upper West Side South,Upper West Side South,2019-03-04,16:11:55,...,True,False,False,False,True,False,False,False,False,False
2,1,1.37,7.5,2.36,0.0,14.16,Alphabet City,West Village,2019-03-27,17:53:01,...,True,False,False,False,False,False,False,False,False,True
3,1,7.70,27.0,6.15,0.0,36.95,Hudson Sq,Yorkville West,2019-03-10,01:23:59,...,True,False,False,False,False,False,True,False,False,False
4,3,2.16,9.0,1.10,0.0,13.40,Midtown East,Yorkville West,2019-03-30,13:27:42,...,True,False,False,False,False,True,False,False,False,False

In [ ]:
print("Unique pickup zones:", data['pickup_zone'].nunique())
print("Unique dropoff zones:", data['dropoff_zone'].nunique())

Unique pickup zones: 195
Unique dropoff zones: 204

**Identifying outliers**

In [ ]:
import numpy as np
import pandas as pd

# Select numerical columns only
numerical_cols = data_encoded.select_dtypes(include=[np.number]).columns

# Store outlier summary
outlier_summary = {}

for col in numerical_cols:
    Q1 = data_encoded[col].quantile(0.25)
    Q3 = data_encoded[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data_encoded[(data_encoded[col] < lower_bound) | (data_encoded[col] > upper_bound)]
    outlier_summary[col] = len(outliers)

# Print result
print("Outliers per column (IQR method):")
for col, count in outlier_summary.items():
    print(f"{col}: {count} outliers")

Outliers per column (IQR method):
passengers: 540 outliers
distance: 734 outliers
fare: 592 outliers
tip: 280 outliers
tolls: 350 outliers
total: 600 outliers
pickup_hour: 0 outliers
dropoff_hour: 0 outliers

**Caping outliers**

In [ ]:
# List of numerical columns to cap outliers
numerical_cols = ['passengers', 'distance', 'fare', 'tip', 'tolls', 'total']

# Apply IQR capping to each numerical column
for col in numerical_cols:
    Q1 = data_encoded[col].quantile(0.25)
    Q3 = data_encoded[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    data_encoded[col] = data_encoded[col].clip(lower=lower_bound, upper=upper_bound)

# Optional: Check result
data_encoded[numerical_cols].describe()

        passengers     distance         fare          tip   tolls        total
count  6433.000000  6433.000000  6433.000000  6433.000000  6433.0  6433.000000
mean      1.421576     2.402856    11.730843     1.833852     0.0    16.724455
std       0.796417     1.948847     7.156878     1.900430     0.0     8.157420
min       1.000000     0.000000     1.000000     0.000000     0.0     1.300000
25%       1.000000     0.980000     6.500000     0.000000     0.0    10.800000
50%       1.000000     1.640000     9.500000     1.700000     0.0    14.160000
75%       2.000000     3.210000    15.000000     2.800000     0.0    20.300000
max       3.500000     6.555000    27.750000     7.000000     0.0    34.550000

In [ ]:
data.head()

,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,pickup_date,pickup_time,pickup_hour,pickup_dayofweek,dropoff_date,dropoff_time,dropoff_hour
0,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,2019-03-23,20:21:09,20,Saturday,2019-03-23,20:27:24,20
1,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,2019-03-04,16:11:55,16,Monday,2019-03-04,16:19:00,16
2,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,2019-03-27,17:53:01,17,Wednesday,2019-03-27,18:00:25,18
3,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,2019-03-10,01:23:59,1,Sunday,2019-03-10,01:49:51,1
4,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,2019-03-30,13:27:42,13,Saturday,2019-03-30,13:37:14,13

In [ ]:
import pandas as pd
data_encoded = data.copy()

# Convert pickup and dropoff dates to datetime
data_encoded['pickup_date'] = pd.to_datetime(data_encoded['pickup_date'], errors='coerce')
data_encoded['dropoff_date'] = pd.to_datetime(data_encoded['dropoff_date'], errors='coerce')

data_encoded['pickup_date'] = data_encoded['pickup_date'].apply(lambda x: x.toordinal() if pd.notnull(x) else x)
data_encoded['dropoff_date'] = data_encoded['dropoff_date'].apply(lambda x: x.toordinal() if pd.notnull(x) else x)

**Encoding the Data some Label encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# Label encode pickup/dropoff zones
label_cols = ['pickup_zone', 'dropoff_zone']
le = LabelEncoder()
for col in label_cols:
    data_encoded[col] = le.fit_transform(data_encoded[col])

#  One-hot encode other categorical columns
categorical_cols = ['color', 'payment', 'pickup_dayofweek', 'pickup_borough', 'dropoff_borough']
data_encoded = pd.get_dummies(data_encoded, columns=categorical_cols, drop_first=True)
data_encoded = data_encoded.drop(['pickup_time', 'dropoff_time'], axis=1)

**Applying Min max scalar**

In [ ]:
scale_cols = [
    'pickup_zone', 'dropoff_zone', 'passengers', 'distance',
    'fare', 'tip', 'tolls', 'pickup_hour', 'dropoff_hour',
    'pickup_date', 'dropoff_date'
]
scaler = MinMaxScaler()
data_encoded[scale_cols] = scaler.fit_transform(data_encoded[scale_cols])

**Training the data**

In [ ]:
from sklearn.model_selection import train_test_split
X = data_encoded.drop('total', axis=1)
y = data_encoded['total']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**Applying sequential model**

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

**Compiling and fitting the data **

In [ ]:
model.compile(optimizer='adam', loss='mse', metrics=['mse'])
model.fit(X_train, y_train, validation_split=0.2, epochs=20, batch_size=32, verbose=2)

Epoch 1/20
129/129 - 5s - 39ms/step - loss: 288.8994 - mse: 288.8994 - val_loss: 155.6374 - val_mse: 155.6374
Epoch 2/20
129/129 - 2s - 15ms/step - loss: 133.8376 - mse: 133.8376 - val_loss: 95.6296 - val_mse: 95.6296
Epoch 3/20
129/129 - 0s - 3ms/step - loss: 66.9863 - mse: 66.9863 - val_loss: 32.7467 - val_mse: 32.7467
Epoch 4/20
129/129 - 1s - 5ms/step - loss: 20.4640 - mse: 20.4640 - val_loss: 12.6671 - val_mse: 12.6671
Epoch 5/20
129/129 - 1s - 5ms/step - loss: 9.6148 - mse: 9.6148 - val_loss: 8.7135 - val_mse: 8.7135
Epoch 6/20
129/129 - 1s - 5ms/step - loss: 7.1647 - mse: 7.1647 - val_loss: 7.0962 - val_mse: 7.0962
Epoch 7/20
129/129 - 1s - 5ms/step - loss: 6.2314 - mse: 6.2314 - val_loss: 6.6046 - val_mse: 6.6046
Epoch 8/20
129/129 - 1s - 5ms/step - loss: 5.6116 - mse: 5.6116 - val_loss: 5.4313 - val_mse: 5.4313
Epoch 9/20
129/129 - 0s - 3ms/step - loss: 4.9418 - mse: 4.9418 - val_loss: 4.8873 - val_mse: 4.8873
Epoch 10/20
129/129 - 1s - 5ms/step - loss: 4.2676 - mse: 4.2676 - val_loss: 4.2251 - val_mse: 4.2251
Epoch 11/20
129/129 - 0s - 3ms/step - loss: 3.8530 - mse: 3.8530 - val_loss: 3.9058 - val_mse: 3.9058
Epoch 12/20
129/129 - 0s - 3ms/step - loss: 3.4155 - mse: 3.4155 - val_loss: 3.7254 - val_mse: 3.7254
Epoch 13/20
129/129 - 1s - 5ms/step - loss: 2.8968 - mse: 2.8968 - val_loss: 3.4758 - val_mse: 3.4758
Epoch 14/20
129/129 - 0s - 3ms/step - loss: 2.6202 - mse: 2.6202 - val_loss: 2.5548 - val_mse: 2.5548
Epoch 15/20
129/129 - 0s - 4ms/step - loss: 2.3307 - mse: 2.3307 - val_loss: 2.1761 - val_mse: 2.1761
Epoch 16/20
129/129 - 0s - 4ms/step - loss: 1.9217 - mse: 1.9217 - val_loss: 2.4212 - val_mse: 2.4212
Epoch 17/20
129/129 - 0s - 4ms/step - loss: 1.7020 - mse: 1.7020 - val_loss: 1.5775 - val_mse: 1.5775
Epoch 18/20
129/129 - 1s - 5ms/step - loss: 1.4589 - mse: 1.4589 - val_loss: 1.4855 - val_mse: 1.4855
Epoch 19/20
129/129 - 1s - 4ms/step - loss: 1.2624 - mse: 1.2624 - val_loss: 1.0944 - val_mse: 1.0944
Epoch 20/20
129/129 - 1s - 5ms/step - loss: 1.0247 - mse: 1.0247 - val_loss: 1.0506 - val_mse: 1.0506